image: ghcr.io/kaniko-build/dist/osscontainertools-kaniko/executor:latest-debug

variables:
  BUILD_DIR: 'api'

stages:
  - build-and-push

build-and-push-job:
  stage: build-and-push
  variables:
    GODEBUG: 'http2client=0'
  script:
    # - echo "=== CI Variables ===" && env | grep -E "^CI_" | sort
    # - echo "=== BUILD_DIR ===" && echo "BUILD_DIR=$BUILD_DIR"
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --cache=true
      --push-retry=10
      --context $CI_PROJECT_DIR/$BUILD_DIR
      --dockerfile $CI_PROJECT_DIR/$BUILD_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE/$BUILD_DIR:$CI_COMMIT_SHORT_SHA
      --destination $CI_REGISTRY_IMAGE/$BUILD_DIR:latest
